version: '3.0'

services:
  tor:
    image: docker.io/szokekaroly/tor:arm
    build:
      context: .
      dockerfile: Dockerfile.arm
    ports:
      - 9050:9050
    volumes:
      - tor:/var/lib/tor

volumes:
  tor: